# Generated by Django 5.1.1 on 2024-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=100)),
                ('metal_type', models.CharField()),
                ('description', models.TextField(max_length=500)),
                ('denomination', models.CharField(max_length=100)),
            ],
        ),
    ]
